void __VERIFIER_assert(int cond) { if(!(cond)) { ERROR: {abort();} } }

/* Generated by Frama-C */
extern void __VERIFIER_assert(int);

int main(void)
{
  int __retres;
  int x = 5;
  int y = 6;
  __VERIFIER_assert(x == y);
  ;
  if (x == y) {
    int y_0 = 6;
  }
  else {
    int y_1 = 7;
  }
  __retres = 0;
  return __retres;
}


