/* Generated by Frama-C */
void __VERIFIER_assume();

int main(void)
{
  int __retres;
  int x = 1;
  __VERIFIER_assume();
  ;
  if (x == 1) {
    int y = 6;
  }
  else {
    int y_0 = 7;
  }
  __retres = 0;
  return __retres;
}


