/* Generated by Frama-C */
void __VERIFIER_assert();

int main(void)
{
  int __retres;
  int x;
  __VERIFIER_assert(x == 100);
  ;
  if (x == 1) {
    int y = 6;
  }
  else {
    int y_0 = 7;
  }
  __retres = 0;
  return __retres;
}


